<a href="https://colab.research.google.com/github/AkhilVinayakp/Deep_learning/blob/main/pytorch_ler1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
from torch import nn

In [ ]:
class LogReg(nn.Model):
  def __init__(self, inp):
    super().__init__()
    self.log_reg = nn.Sequential(
        nn.Linear(inp, 1),
        nn.Sigmoid() # activation
    )
    def forward(self, x):
      return self.log_reg(x)
    

In [1]:
# getting started with tenso

In [2]:
import torch

In [3]:
data = [
        [1,2],
        [2,4]
]

In [4]:
ten = torch.Tensor(data)

In [5]:
ten

tensor([[1., 2.],
        [2., 4.]])

In [6]:
example_tensor = torch.Tensor(
    [
     [[1, 2], [3, 4]], 
     [[5, 6], [7, 8]], 
     [[9, 0], [1, 2]]
    ]
)

In [7]:
example_tensor

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]],

        [[9., 0.],
         [1., 2.]]])

In [8]:
ten.device

device(type='cpu')

In [9]:
ten.shape

torch.Size([2, 2])

In [12]:
ex = torch.Tensor(
    [
     [[1, 2], [3, 4]], 
     [[5, 6], [7, 8]], 
     [[9, 0], [1, 2]]
    ]
)

In [13]:
ex.shape

torch.Size([3, 2, 2])

In [15]:
#  dimensions (rank) or the number of elements in a tensor
print(len(ex.shape), ex.numel())

3 12


In [21]:
# indexing tensor using[]
print(ex[1]) # values from first dim
# getting the single element as a tensor
print(ex[1,1,1]) # will return as tensor one element 
# converting the element to a scalar value
print(ex[1,1,1].item())

tensor([[5., 6.],
        [7., 8.]])
tensor(8.)
8.0


In [23]:
# Tensor initialization methods
# way 1 direct from data as above
# way two from another tensor (by the same shape and device)
# by specifing the shape and device



In [24]:
# initilization using already existing tensor >> follows same shape and device

# initializing wih 0 using zero_like and with 1 by using one_like
# initializing with randn_like creates a tensor with every element sampled from a Normal (or Gaussian) distribution 


In [31]:
x = [
     [[1,3],[2,4]],
     [[6,7],[0,5]]
     ]
# torch.one_like
x = torch.Tensor(x)
one = torch.ones_like(x)
print(one, one.shape, one.device)
zero = torch.zeros_like(x)
print(zero, zero.shape, zero.device)



tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]]) torch.Size([2, 2, 2]) cpu
tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]) torch.Size([2, 2, 2]) cpu
