<a href="https://colab.research.google.com/github/AkhilVinayakp/Deep_learning/blob/main/TimeSeries.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras

In [ ]:
# additional installation
!pip install -U tf-nightly

     |████████████████████████████████| 410.0MB 42kB/s 
     |████████████████████████████████| 6.1MB 43.8MB/s 
     |████████████████████████████████| 471kB 44.5MB/s 
     |████████████████████████████████| 4.0MB 41.1MB/s 
     |████████████████████████████████| 4.0MB 27.4MB/s 
     |████████████████████████████████| 3.8MB 54.4MB/s 
ERROR: tensorflow 2.4.1 has requirement gast==0.3.3, but you'll have gast 0.4.0 which is incompatible.
ERROR: tensorflow 2.4.1 has requirement grpcio~=1.32.0, but you'll have grpcio 1.34.1 which is incompatible.
ERROR: tensorflow 2.4.1 has requirement h5py~=2.10.0, but you'll have h5py 3.1.0 which is incompatible.
  Found existing installation: grpcio 1.32.0
    Uninstalling grpcio-1.32.0:
      Successfully uninstalled grpcio-1.32.0
  Found existing installation: h5py 2.10.0
    Uninstalling h5py-2.10.0:
      Successfully uninstalled h5py-2.10.0
  Found existing installation: gast 0.3.3
    Uninstalling gast-0.3.3:
      Successfully uninstalled gast-0.3

In [ ]:
print(tf.__version__)

2.4.1


In [ ]:
def plot_time_data(time, series, format="-", start = 0, end = None, label = None):
  """plot a time series data"""
  plt.plot(time[start:end], series[start:end], format, label)
  plt.xlabel("time")
  plt.ylabel("Values")
  if label:
    plt.legend()
  plt.grid(True)

In [ ]:
# testing data windowing
import tensorflow as tf

In [ ]:
import numpy as np

In [ ]:
dataset = tf.data.Dataset.range(10)

In [ ]:
for val in dataset:
  print(val.numpy())

0
1
2
3
4
5
6
7
8
9


In [ ]:
# windowing 
dataset = dataset.window(4,shift=2)

In [ ]:
for window_data in dataset:
  print("Windowed data")
  for val in window_data:
    print(val.numpy(), end = ' ')
  print()

Windowed data
0 1 2 3 
Windowed data
2 3 4 5 
Windowed data
4 5 6 7 
Windowed data
6 7 8 9 
Windowed data
8 9 


In [ ]:
# regularly sized windows
dataset = tf.data.Dataset.range(40)
dataset = dataset.window(6,shift=3, drop_remainder=True)
for window_data in dataset:
  print("Windowed data")
  for val in window_data:
    print(val.numpy(), end = ' ')
  print()

Windowed data
0 1 2 3 4 5 
Windowed data
3 4 5 6 7 8 
Windowed data
6 7 8 9 10 11 
Windowed data
9 10 11 12 13 14 
Windowed data
12 13 14 15 16 17 
Windowed data
15 16 17 18 19 20 
Windowed data
18 19 20 21 22 23 
Windowed data
21 22 23 24 25 26 
Windowed data
24 25 26 27 28 29 
Windowed data
27 28 29 30 31 32 
Windowed data
30 31 32 33 34 35 
Windowed data
33 34 35 36 37 38 


In [ ]:
# creating the numpylist for the window
# regularly sized windows
dataset = tf.data.Dataset.range(40)
dataset = dataset.window(6,shift=3, drop_remainder=True)
dataset = dataset.flat_map(lambda window : window.batch(6))
for window in dataset:
  print("window data")
  print(window.numpy())

window data
[0 1 2 3 4 5]
window data
[3 4 5 6 7 8]
window data
[ 6  7  8  9 10 11]
window data
[ 9 10 11 12 13 14]
window data
[12 13 14 15 16 17]
window data
[15 16 17 18 19 20]
window data
[18 19 20 21 22 23]
window data
[21 22 23 24 25 26]
window data
[24 25 26 27 28 29]
window data
[27 28 29 30 31 32]
window data
[30 31 32 33 34 35]
window data
[33 34 35 36 37 38]


In [ ]:
# splitting into features and labels
# consider the first five as features and last one as the label
dataset = tf.data.Dataset.range(40)
dataset = dataset.window(6,shift=3, drop_remainder=True)
dataset = dataset.flat_map(lambda window : window.batch(6))
# after creating the window batches use map to map the features and labels
dataset =  dataset.map(lambda window: (window[:-1],window[-1:]))
# printing out the data
for x, y in dataset:
  print(x.numpy(), y.numpy())

[0 1 2 3 4] [5]
[3 4 5 6 7] [8]
[ 6  7  8  9 10] [11]
[ 9 10 11 12 13] [14]
[12 13 14 15 16] [17]
[15 16 17 18 19] [20]
[18 19 20 21 22] [23]
[21 22 23 24 25] [26]
[24 25 26 27 28] [29]
[27 28 29 30 31] [32]
[30 31 32 33 34] [35]
[33 34 35 36 37] [38]


In [ ]:
# the data often shuffled 
# can be done using .shuffle(buffer_size = n)  method
dataset = tf.data.Dataset.range(40)
dataset = dataset.window(6,shift=3, drop_remainder=True)
dataset = dataset.flat_map(lambda window : window.batch(6))
dataset =  dataset.map(lambda window: (window[:-1],window[-1:]))
# shuffling the values
dataset = dataset.shuffle(buffer_size=10) # the buffer_size ?
# printing out the data
for x, y in dataset:
  print(x.numpy(), y.numpy())

[18 19 20 21 22] [23]
[ 6  7  8  9 10] [11]
[30 31 32 33 34] [35]
[33 34 35 36 37] [38]
[ 9 10 11 12 13] [14]
[15 16 17 18 19] [20]
[12 13 14 15 16] [17]
[24 25 26 27 28] [29]
[27 28 29 30 31] [32]
[0 1 2 3 4] [5]
[21 22 23 24 25] [26]
[3 4 5 6 7] [8]


In [ ]:
# the data often load as batches
# batches can be created by using batch() method
dataset = tf.data.Dataset.range(40)
dataset = dataset.window(6,shift=3, drop_remainder=True)
dataset = dataset.flat_map(lambda window : window.batch(6))
dataset =  dataset.map(lambda window: (window[:-1],window[-1:]))
# shuffling the values
dataset = dataset.shuffle(buffer_size=40)
# creating the batches
dataset = dataset.batch(2).prefetch(1) # the value of prefetch ?
# printing out the data
for x, y in dataset:
  print("x = ", x.numpy())
  print("y = ", y.numpy())

x =  [[24 25 26 27 28]
 [12 13 14 15 16]]
y =  [[29]
 [17]]
x =  [[0 1 2 3 4]
 [3 4 5 6 7]]
y =  [[5]
 [8]]
x =  [[18 19 20 21 22]
 [21 22 23 24 25]]
y =  [[23]
 [26]]
x =  [[33 34 35 36 37]
 [27 28 29 30 31]]
y =  [[38]
 [32]]
x =  [[30 31 32 33 34]
 [ 9 10 11 12 13]]
y =  [[35]
 [14]]
x =  [[15 16 17 18 19]
 [ 6  7  8  9 10]]
y =  [[20]
 [11]]


In [ ]:
# function to return the windowed dataset
def windowed_dataset(series, window_size,shift_size, batch_size,shuffle_buffer):
  dataset = tf.data.Dataset.from_tensor_slices(series)
  dataset = dataset.window(window_size +1, shift = shift_size, drop_remainder = True)
  dataset = dataset.flat_map(lambda window: window.batch(window_size+1))
  dataset = dataset.shuffle(shuffle_buffer).map(lambda window :  (window[:-1], window[-1]))
  dataset = dataset.batch(batch_size).prefetch(1)
  return dataset

In [ ]:
def trend(time, slope=0):
    return slope * time

def seasonal_pattern(season_time):
    """Just an arbitrary pattern, you can change it if you wish"""
    return np.where(season_time < 0.4,
                    np.cos(season_time * 2 * np.pi),
                    1 / np.exp(3 * season_time))

def seasonality(time, period, amplitude=1, phase=0):
    """Repeats the same pattern at each period"""
    season_time = ((time + phase) % period) / period
    return amplitude * seasonal_pattern(season_time)

def noise(time, noise_level=1, seed=None):
    rnd = np.random.RandomState(seed)
    return rnd.randn(len(time)) * noise_level

time = np.arange(4 * 365 + 1, dtype="float32")
baseline = 10
series = trend(time, 0.1)  
baseline = 10
amplitude = 40
slope = 0.05
noise_level = 5

# Create the series
series = baseline + trend(time, slope) + seasonality(time, period=365, amplitude=amplitude)
# Update with noise
series += noise(time, noise_level, seed=42)

In [ ]:
series.shape

(1461,)

In [ ]:
type(series)

numpy.ndarray

In [ ]:
time.shape

(1461,)

In [ ]:
# creating split for trining and testing
split_time = 1000
time_train = time[:split_time]
x_train = series[:split_time]

# for testing 
time_valid = time[split_time:]
x_valid = series[split_time:]

In [ ]:
# creating the windowed data from series
dataset = windowed_dataset(x_train, window_size=20, shift_size= 1, batch_size=32, shuffle_buffer=1000)
# regression model
# single dense layer 
L0 = tf.keras.layers.Dense(1,input_shape = [20])
# defining the model 
model = tf.keras.models.Sequential([L0])

In [ ]:
# trining the model 
model.compile(loss="mse", optimizer=tf.keras.optimizers.SGD(lr=1e-6, momentum=0.9))
model.fit(dataset,epochs=100,verbose=0)

print("Layer weights {}".format(L0.get_weights()))

Layer weights [array([[-0.02214744],
       [-0.07615466],
       [ 0.10335191],
       [-0.03430599],
       [-0.00763742],
       [ 0.08394616],
       [ 0.00252062],
       [-0.071883  ],
       [ 0.00933745],
       [ 0.00254631],
       [-0.03578468],
       [ 0.07111982],
       [-0.06596499],
       [-0.01594495],
       [ 0.0995695 ],
       [ 0.05201309],
       [-0.00174174],
       [ 0.14563236],
       [ 0.34470424],
       [ 0.39630368]], dtype=float32), array([0.0155364], dtype=float32)]


In [ ]:
# predicting the values
test = x_valid[1:21][np.newaxis] 

In [ ]:
print(type(test), test.shape)

<class 'numpy.ndarray'> (1, 20)


In [ ]:
test

array([[68.98552 , 64.6752  , 61.15736 , 67.89844 , 66.390305, 68.91469 ,
        67.6307  , 69.71901 , 61.81174 , 71.091835, 65.51008 , 74.91588 ,
        61.11138 , 73.25516 , 65.58317 , 61.35506 , 62.21152 , 63.048264,
        66.79013 , 67.30303 ]], dtype=float32)

In [ ]:
model.predict(test)

array([[65.02351]], dtype=float32)

In [ ]:
test = x_valid[21:41][np.newaxis] # newaxis is to deal with the imput size
model.predict(test)

array([[70.44973]], dtype=float32)

(21,)

In [ ]:
forcast = []
for time in range(len(x_train)- 20):
  pass
  # forcast.append(model.predict(x_train[]))
  # todo